# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Operable
tagline:             'Creators of COG!'
description:         'Words about Operable and the creation of Cog, the most amazing bot known to humans.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            2
logo:

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
