# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shelton
email: sheltonjdavis@gmail.com
description: Getting use to this stuff...let's break and fix things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shelton.github.io" # the base hostname & protocol for your site
twitter_username: shelton
github_username:  shelton

# Build settings
markdown: kramdown
